language: common-lisp

sudo: required

env:
  matrix:
    - LISP=sbcl COVERALLS=true
    - LISP=ccl
    # CLISP and ECL seem to be unsupported by CL-COVERALLS at this time
    # - LISP=clisp
    # - LISP=ecl
    - LISP=abcl

install:
  - if [ -x ./install.sh ] && head -2 ./install.sh | grep '^# cl-travis' > /dev/null;
    then
      ./install.sh;
    else
      curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
    fi
  # Coveralls support
  - git clone https://github.com/fukamachi/cl-coveralls ~/lisp/cl-coveralls

script:
  - cl -l prove -l cl-coveralls
       -e '(in-package :cl-user)'
       -e '(ql:quickload :cl-cuneiform)'
       -e '(setf prove:*debug-on-error* t)'
       -e '(setf *debugger-hook*
                 (lambda (c h)
                   (declare (ignore c h))
                   (uiop:quit -1)))'
       -e '(coveralls:with-coveralls (:exclude (list "t"))
             (or (prove:run :cl-cuneiform-test)
               (uiop:quit -1)))'
